// examples/svelte-app/src/App.svelte
<script lang="ts">
  import { createFlagsStore, createUserIdStore, createOverridesStore, trackError } from '@otto-flags/svelte';
  import FlagOverridePanel from './FlagOverridePanel.svelte';

  /**
   * Feature Demo Component
   * Demonstrates best practices for using Otto Flags Svelte SDK
   */

  // Per SDK Developer Guide: Use createFlagsStore for multiple flags in the same component
  const flags = createFlagsStore(
    ['new-feature', 'beta-feature', 'enterprise-one'],
    {
      defaultValues: {
        'new-feature': false,
        'beta-feature': false,
        'enterprise-one': false,
      },
      realtime: true,
    }
  );

  // Reactive user ID store
  const userId = createUserIdStore();

  // Reactive overrides store for UI reactivity
  const overrides = createOverridesStore();

  // Example error handler demonstrating error tracking
  async function handleRiskyAction() {
    try {
      // Simulated action that might fail
      throw new Error('Example error for demonstration');
    } catch (error) {
      // Track errors for AI-powered correlation
      trackError('new-feature', error as Error);
      console.error('Action failed:', error);
    }
  }

  // User management handlers
  function setRandomUserId() {
    $userId = 'user-' + Date.now();
  }

  function clearUserId() {
    $userId = null;
  }

  // Reactive statements for override status - using $overrides for reactivity
  $: newFeatureOverridden = 'new-feature' in $overrides.overrides;
  $: betaFeatureOverridden = 'beta-feature' in $overrides.overrides;
  $: enterpriseOneOverridden = 'enterprise-one' in $overrides.overrides;
</script>

<div class="container">
  <h1>Otto Flags Svelte Example</h1>
  <p class="subtitle">SDK Developer Guide Best Practices Demo</p>

  {#if $flags.loading}
    <p class="loading">Loading feature flags...</p>
  {:else}
    <div>
      {#key $overrides.count}
      <div class="feature-card" class:feature-card-overridden={newFeatureOverridden}>
        <h2>
          New Feature
          {#if newFeatureOverridden}
            <span class="override-badge-inline">LOCAL OVERRIDE</span>
          {/if}
        </h2>
        <p>
          Status:
          <span class="status" class:enabled={$flags.values['new-feature']} class:disabled={!$flags.values['new-feature']}>
            {$flags.values['new-feature'] ? 'Enabled' : 'Disabled'}
          </span>
        </p>
        {#if newFeatureOverridden}
          <p class="server-value">
            Server value: {$flags.values['new-feature'] ? 'Enabled' : 'Disabled'}
          </p>
        {/if}
        {#if $flags.results['new-feature']?.metadata?.variation}
          <p class="variation">
            Variation: {$flags.results['new-feature'].metadata.variation}
          </p>
        {/if}
        {#if $flags.results['new-feature']?.metadata?.configuration}
          <p class="config">
            Config: <code>{JSON.stringify($flags.results['new-feature'].metadata.configuration)}</code>
          </p>
        {/if}
      </div>

      <div class="feature-card" class:feature-card-overridden={betaFeatureOverridden}>
        <h2>
          Beta Feature
          {#if betaFeatureOverridden}
            <span class="override-badge-inline">LOCAL OVERRIDE</span>
          {/if}
        </h2>
        <p>
          Status:
          <span class="status" class:enabled={$flags.values['beta-feature']} class:disabled={!$flags.values['beta-feature']}>
            {$flags.values['beta-feature'] ? 'Enabled' : 'Disabled'}
          </span>
        </p>
        {#if betaFeatureOverridden}
          <p class="server-value">
            Server value: {$flags.values['beta-feature'] ? 'Enabled' : 'Disabled'}
          </p>
        {/if}
        {#if $flags.results['beta-feature']?.metadata?.variation}
          <p class="variation">
            Variation: {$flags.results['beta-feature'].metadata.variation}
          </p>
        {/if}
      </div>

      <div class="feature-card" class:feature-card-overridden={enterpriseOneOverridden}>
        <h2>
          Enterprise One
          {#if enterpriseOneOverridden}
            <span class="override-badge-inline">LOCAL OVERRIDE</span>
          {/if}
        </h2>
        <p>
          Status:
          <span class="status" class:enabled={$flags.values['enterprise-one']} class:disabled={!$flags.values['enterprise-one']}>
            {$flags.values['enterprise-one'] ? 'Enabled' : 'Disabled'}
          </span>
        </p>
        {#if enterpriseOneOverridden}
          <p class="server-value">
            Server value: {$flags.values['enterprise-one'] ? 'Enabled' : 'Disabled'}
          </p>
        {/if}
        {#if $flags.results['enterprise-one']?.metadata?.variation}
          <p class="variation">
            Variation: {$flags.results['enterprise-one'].metadata.variation}
          </p>
        {/if}
        {#if $flags.results['enterprise-one']?.metadata?.configuration}
          <p class="config">
            Config: <code>{JSON.stringify($flags.results['enterprise-one'].metadata.configuration)}</code>
          </p>
        {/if}
      </div>
      {/key}

      {#if $flags.values['new-feature']}
        <div class="alert alert-success">
          <strong>New Feature Enabled!</strong>
          <p>This feature is enabled for you based on your user attributes.</p>
          <button on:click={handleRiskyAction} class="btn">
            Test Error Tracking
          </button>
        </div>
      {/if}

      <div class="user-section">
        <h3>User Management</h3>
        <p>Current User ID: <code>{$userId || 'Not set'}</code></p>
        <button on:click={setRandomUserId} class="btn">
          Set Random User ID
        </button>
        <button on:click={clearUserId} class="btn btn-secondary">
          Clear User ID
        </button>
      </div>
    </div>
  {/if}
</div>

<FlagOverridePanel />

// examples/vue-app/src/App.vue
<script setup lang="ts">
import { useFlags, useUser, useTrackError, useOttoFlags } from '@otto-flags/vue';
import FlagOverridePanel from './FlagOverridePanel.vue';

/**
 * Feature Demo Component
 * Demonstrates best practices for using Otto Flags Vue SDK
 *
 * Uses the useFlags composable for optimal performance - evaluates multiple flags
 * with a single state update, preventing unnecessary re-renders.
 */

const { client } = useOttoFlags();

// Per SDK Developer Guide: Use useFlags for multiple flags in the same component
// This is more performant than multiple useFlag calls as it:
// 1. Uses a single reactive object for atomic updates
// 2. Evaluates all flags in parallel
// 3. Only triggers one re-render when any flag changes
// 4. Automatically respects local overrides set via client.setOverride()
const { values, loading, results } = useFlags(
  ['new-feature', 'beta-feature', 'enterprise-one'],
  {
    defaultValues: {
      'new-feature': false,
      'beta-feature': false,
      'enterprise-one': false,
    },
    realtime: true, // Enable real-time updates for all flags
  }
);

// Hook for error tracking - per SDK Developer Guide telemetry
const trackError = useTrackError('new-feature');

// Hook for user management - userId is reactive
const { userId, setUserId } = useUser();

// Example error handler demonstrating error tracking
const handleRiskyAction = async () => {
  try {
    // Simulated action that might fail
    throw new Error('Example error for demonstration');
  } catch (error) {
    // Track errors for AI-powered correlation
    trackError(error as Error);
    console.error('Action failed:', error);
  }
};

// User management handlers
const setRandomUserId = () => {
  setUserId('user-' + Date.now());
};

const clearUserId = () => {
  setUserId(null);
};

// Check if flags are overridden (for UI indication)
const isOverridden = (flagKey: string): boolean => {
  return client?.hasOverride(flagKey) ?? false;
};
</script>

<template>
  <div class="container">
    <h1>Otto Flags Vue Example</h1>
    <p class="subtitle">SDK Developer Guide Best Practices Demo</p>

    <p v-if="loading" class="loading">Loading feature flags...</p>

    <div v-else>
      <div
        :class="['feature-card', { 'feature-card-overridden': isOverridden('new-feature') }]"
      >
        <h2>
          New Feature
          <span v-if="isOverridden('new-feature')" class="override-badge-inline">LOCAL OVERRIDE</span>
        </h2>
        <p>
          Status:
          <span :class="['status', values['new-feature'] ? 'enabled' : 'disabled']">
            {{ values['new-feature'] ? 'Enabled' : 'Disabled' }}
          </span>
        </p>
        <p v-if="isOverridden('new-feature')" class="server-value">
          Server value: {{ values['new-feature'] ? 'Enabled' : 'Disabled' }}
        </p>
        <p v-if="results['new-feature']?.metadata?.variation" class="variation">
          Variation: {{ results['new-feature'].metadata.variation }}
        </p>
        <p v-if="results['new-feature']?.metadata?.configuration" class="config">
          Config: <code>{{ JSON.stringify(results['new-feature'].metadata.configuration) }}</code>
        </p>
      </div>

      <div
        :class="['feature-card', { 'feature-card-overridden': isOverridden('beta-feature') }]"
      >
        <h2>
          Beta Feature
          <span v-if="isOverridden('beta-feature')" class="override-badge-inline">LOCAL OVERRIDE</span>
        </h2>
        <p>
          Status:
          <span :class="['status', values['beta-feature'] ? 'enabled' : 'disabled']">
            {{ values['beta-feature'] ? 'Enabled' : 'Disabled' }}
          </span>
        </p>
        <p v-if="isOverridden('beta-feature')" class="server-value">
          Server value: {{ values['beta-feature'] ? 'Enabled' : 'Disabled' }}
        </p>
        <p v-if="results['beta-feature']?.metadata?.variation" class="variation">
          Variation: {{ results['beta-feature'].metadata.variation }}
        </p>
      </div>

      <div
        :class="['feature-card', { 'feature-card-overridden': isOverridden('enterprise-one') }]"
      >
        <h2>
          Enterprise One
          <span v-if="isOverridden('enterprise-one')" class="override-badge-inline">LOCAL OVERRIDE</span>
        </h2>
        <p>
          Status:
          <span :class="['status', values['enterprise-one'] ? 'enabled' : 'disabled']">
            {{ values['enterprise-one'] ? 'Enabled' : 'Disabled' }}
          </span>
        </p>
        <p v-if="isOverridden('enterprise-one')" class="server-value">
          Server value: {{ values['enterprise-one'] ? 'Enabled' : 'Disabled' }}
        </p>
        <p v-if="results['enterprise-one']?.metadata?.variation" class="variation">
          Variation: {{ results['enterprise-one'].metadata.variation }}
        </p>
        <p v-if="results['enterprise-one']?.metadata?.configuration" class="config">
          Config: <code>{{ JSON.stringify(results['enterprise-one'].metadata.configuration) }}</code>
        </p>
      </div>

      <div v-if="values['new-feature']" class="alert alert-success">
        <strong>New Feature Enabled!</strong>
        <p>This feature is enabled for you based on your user attributes.</p>
        <button @click="handleRiskyAction" class="btn">
          Test Error Tracking
        </button>
      </div>

      <div class="user-section">
        <h3>User Management</h3>
        <p>Current User ID: <code>{{ userId || 'Not set' }}</code></p>
        <button @click="setRandomUserId" class="btn">
          Set Random User ID
        </button>
        <button @click="clearUserId" class="btn btn-secondary">
          Clear User ID
        </button>
      </div>
    </div>
  </div>

  <FlagOverridePanel />
</template>
